In [2]:
import sqlite3
import pandas as pd
import os

BASE_DIR = os.getcwd()
DB_PATH = os.path.join(BASE_DIR, "nstar.db")

conn = sqlite3.connect(DB_PATH)

print("Connected to NSTAR database.")

Connected to NSTAR database.

In [6]:
inventory = pd.read_sql_query("""
    SELECT
        p.sku AS "SKU",
        p.product_name AS "Product Name",
        p.category AS "Category",
        i.quantity AS "Quantity",
        i.minimum_stock AS "Minimum Stock",
        i.last_updated AS "Last Updated"
    FROM products p
    JOIN inventory i
        ON p.product_id = i.product_id
    ORDER BY p.product_id
""", conn)

inventory

,SKU,Product Name,Category,Quantity,Minimum Stock,Last Updated
0,NST-001,ecoluxe goods 8oz hot paper cup,Food Service,8,3,2026-10-07 21:30:11
1,NST-002,ecoluxe goods 12oz hot paper cup,Food Service,0,3,2026-10-06 17:58:11
2,NST-003,8 x 8 x 3 bagasse clamshell container - 3 comp...,Food Containers,0,3,2026-10-06 17:58:11
3,NST-004,500pcs 6pc Meal Kit,Food Service,0,3,2026-10-06 17:58:11
4,NST-005,Saporito 16L Canola Oil Pail,Cooking Oil,0,3,2026-10-06 17:58:11
5,NST-006,ADM Flour 20KG,Dry Goods,0,3,2026-10-06 19:05:23
6,NST-007,Redpath 20KG Sugar,Dry Goods,0,3,2026-10-06 17:58:11
7,NST-008,HQ 5 x 5 Clear Hinged Container,Food Containers,0,3,2026-10-06 17:58:11
8,NST-009,eco craze 9 inch bagasse plate,Food Service,0,3,2026-10-06 17:58:11
9,NST-010,9 x 9 x 3 MFPP Clamshell Container,Food Containers,0,3,2026-10-06 17:58:11

In [7]:
transactions = pd.read_sql_query("""
    SELECT
        t.transaction_id AS "ID",
        p.sku AS "SKU",
        p.product_name AS "Product Name",
        t.action AS "Action",
        t.quantity_change AS "Change",
        t.previous_quantity AS "Previous Qty",
        t.new_quantity AS "New Qty",
        t.source AS "Source",
        t.device_id AS "Device",
        t.timestamp AS "Timestamp"
    FROM transactions t
    JOIN products p
        ON t.product_id = p.product_id
    ORDER BY t.transaction_id DESC
""", conn)

transactions

,ID,SKU,Product Name,Action,Change,Previous Qty,New Qty,Source,Device,Timestamp
0,10,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,7,8,RFID,NSTAR-ESP32-01,2026-10-07 21:30:11
1,9,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,6,7,RFID,NSTAR-ESP32-01,2026-10-07 19:18:25
2,8,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,5,6,RFID,NSTAR-ESP32-01,2026-10-07 19:18:22
3,7,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,4,5,RFID,NSTAR-ESP32-01,2026-10-07 17:05:08
4,6,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,3,4,RFID,NSTAR-ESP32-01,2026-10-07 16:38:27
5,5,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,2,3,RFID,NSTAR-ESP32-01,2026-10-07 16:21:06
6,4,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,1,2,RFID,NSTAR-ESP32-01,2026-10-07 16:19:59
7,3,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,0,1,RFID,NSTAR-ESP32-01,2026-10-07 16:19:45
8,2,NST-006,ADM Flour 20KG,REMOVE,-5,5,0,MANUAL,None,2026-10-06 19:05:23
9,1,NST-006,ADM Flour 20KG,ADD,5,0,5,MANUAL,None,2026-10-06 18:25:38

In [8]:
cursor = conn.cursor()

cursor.execute("""
    UPDATE products
    SET rfid_uid = ?
    WHERE sku = ?
""", ("83F74F07", "NST-001"))

conn.commit()

print("RFID card assigned to NST-001.")

RFID card assigned to NST-001.

In [9]:
rfid_assignments = pd.read_sql_query("""
    SELECT
        sku AS "SKU",
        product_name AS "Product Name",
        rfid_uid AS "RFID UID"
    FROM products
    ORDER BY product_id
""", conn)

rfid_assignments

       SKU                                       Product Name  RFID UID
0  NST-001                    ecoluxe goods 8oz hot paper cup  83F74F07
1  NST-002                   ecoluxe goods 12oz hot paper cup      None
2  NST-003  8 x 8 x 3 bagasse clamshell container - 3 comp...      None
3  NST-004                                500pcs 6pc Meal Kit      None
4  NST-005                       Saporito 16L Canola Oil Pail      None
5  NST-006                                     ADM Flour 20KG      None
6  NST-007                                 Redpath 20KG Sugar      None
7  NST-008                    HQ 5 x 5 Clear Hinged Container      None
8  NST-009                     eco craze 9 inch bagasse plate      None
9  NST-010                 9 x 9 x 3 MFPP Clamshell Container      None

In [10]:
transactions = pd.read_sql_query("""
    SELECT
        t.transaction_id AS "ID",
        p.sku AS "SKU",
        p.product_name AS "Product Name",
        t.action AS "Action",
        t.quantity_change AS "Change",
        t.previous_quantity AS "Previous Qty",
        t.new_quantity AS "New Qty",
        t.source AS "Source",
        t.device_id AS "Device",
        t.timestamp AS "Timestamp"
    FROM transactions t
    JOIN products p
        ON t.product_id = p.product_id
    ORDER BY t.transaction_id DESC
""", conn)

transactions

,ID,SKU,Product Name,Action,Change,Previous Qty,New Qty,Source,Device,Timestamp
0,10,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,7,8,RFID,NSTAR-ESP32-01,2026-10-07 21:30:11
1,9,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,6,7,RFID,NSTAR-ESP32-01,2026-10-07 19:18:25
2,8,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,5,6,RFID,NSTAR-ESP32-01,2026-10-07 19:18:22
3,7,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,4,5,RFID,NSTAR-ESP32-01,2026-10-07 17:05:08
4,6,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,3,4,RFID,NSTAR-ESP32-01,2026-10-07 16:38:27
5,5,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,2,3,RFID,NSTAR-ESP32-01,2026-10-07 16:21:06
6,4,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,1,2,RFID,NSTAR-ESP32-01,2026-10-07 16:19:59
7,3,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,0,1,RFID,NSTAR-ESP32-01,2026-10-07 16:19:45
8,2,NST-006,ADM Flour 20KG,REMOVE,-5,5,0,MANUAL,None,2026-10-06 19:05:23
9,1,NST-006,ADM Flour 20KG,ADD,5,0,5,MANUAL,None,2026-10-06 18:25:38

In [11]:
cursor = conn.cursor()

cursor.execute("""
    UPDATE products
    SET rfid_uid = ?
    WHERE sku = ?
""", ("83E74F07", "NST-001"))

conn.commit()

print("RFID UID updated.")

RFID UID updated.

In [12]:
transactions = pd.read_sql_query("""
    SELECT
        t.transaction_id AS "ID",
        p.sku AS "SKU",
        p.product_name AS "Product Name",
        t.action AS "Action",
        t.quantity_change AS "Change",
        t.previous_quantity AS "Previous Qty",
        t.new_quantity AS "New Qty",
        t.source AS "Source",
        t.device_id AS "Device",
        t.timestamp AS "Timestamp"
    FROM transactions t
    JOIN products p
        ON t.product_id = p.product_id
    ORDER BY t.transaction_id DESC
""", conn)

transactions

,ID,SKU,Product Name,Action,Change,Previous Qty,New Qty,Source,Device,Timestamp
0,10,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,7,8,RFID,NSTAR-ESP32-01,2026-10-07 21:30:11
1,9,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,6,7,RFID,NSTAR-ESP32-01,2026-10-07 19:18:25
2,8,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,5,6,RFID,NSTAR-ESP32-01,2026-10-07 19:18:22
3,7,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,4,5,RFID,NSTAR-ESP32-01,2026-10-07 17:05:08
4,6,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,3,4,RFID,NSTAR-ESP32-01,2026-10-07 16:38:27
5,5,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,2,3,RFID,NSTAR-ESP32-01,2026-10-07 16:21:06
6,4,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,1,2,RFID,NSTAR-ESP32-01,2026-10-07 16:19:59
7,3,NST-001,ecoluxe goods 8oz hot paper cup,ADD,1,0,1,RFID,NSTAR-ESP32-01,2026-10-07 16:19:45
8,2,NST-006,ADM Flour 20KG,REMOVE,-5,5,0,MANUAL,None,2026-10-06 19:05:23
9,1,NST-006,ADM Flour 20KG,ADD,5,0,5,MANUAL,None,2026-10-06 18:25:38

In [3]:
inventory = pd.read_sql_query("""
    SELECT
        p.sku AS "SKU",
        p.product_name AS "Product Name",
        p.category AS "Category",
        i.quantity AS "Quantity",
        i.minimum_stock AS "Minimum Stock",
        i.last_updated AS "Last Updated"
    FROM products p
    JOIN inventory i
        ON p.product_id = i.product_id
    ORDER BY p.product_id
""", conn)

inventory

,SKU,Product Name,Category,Quantity,Minimum Stock,Last Updated
0,NST-001,ecoluxe goods 8oz hot paper cup,Food Service,9,3,2026-10-11 18:16:43
1,NST-002,ecoluxe goods 12oz hot paper cup,Food Service,4,3,2026-10-11 18:19:38
2,NST-003,8 x 8 x 3 bagasse clamshell container - 3 comp...,Food Containers,0,3,2026-10-06 17:58:11
3,NST-004,500pcs 6pc Meal Kit,Food Service,0,3,2026-10-06 17:58:11
4,NST-005,Saporito 16L Canola Oil Pail,Cooking Oil,0,3,2026-10-06 17:58:11
5,NST-006,ADM Flour 20KG,Dry Goods,0,3,2026-10-06 19:05:23
6,NST-007,Redpath 20KG Sugar,Dry Goods,0,3,2026-10-06 17:58:11
7,NST-008,HQ 5 x 5 Clear Hinged Container,Food Containers,0,3,2026-10-06 17:58:11
8,NST-009,eco craze 9 inch bagasse plate,Food Service,0,3,2026-10-06 17:58:11
9,NST-010,9 x 9 x 3 MFPP Clamshell Container,Food Containers,0,3,2026-10-06 17:58:11